Feature/notification channel
Studievereniging-Peer2Peer/Discord-Bot pull request #10
Opened 2023-03-17 16:36 UTC by JulianQuispel

Prisma toegevoegd voor verbinding met Postgres

2023-03-17 17:34 UTC, SMWLucasO requested changes
Algemeen, zorg dat berichten in het Nederlands verstuurd worden. Verder is het wel handig om in ieder geval commentaar toe te voegen bij de entiteiten die heen en weer gestuurd worden. Dit mag natuurlijk ook op een andere manier naar keuze, trouwens.

(Deze review is, naast Nederlands gebruik, iets om over na te denken. Niet een 'je moet dit doen')

2023-03-17 17:34 UTC, SMWLucasO commented on src/commands/set.ts
> +        content: 'Please set your birthday in the DD-MM-YYYY format',
Dit mag in het Nederlands

2023-03-17 17:34 UTC, SMWLucasO commented on src/events/birthdays.ts
> +      );
Dit mag ook in het Nederlands.

2023-03-17 17:34 UTC, SMWLucasO commented on src/events/birthdays.ts
> +  // console.log('Sent congratulations');
Deze comment mag weg.

2023-03-17 17:34 UTC, SMWLucasO commented on src/index.ts
> +  cron.schedule('*/30 * * * * *', async () => {
Opmerking van @UnderKoen eerder, is wel heel vaak. Misschien net zoals de huidige birthday bot elke dag om 00:00?

2023-03-17 17:34 UTC, SMWLucasO commented on src/commands/notificationChannel.ts
> +    .setName('notification_channel')
Het is misschien wel interessant om alle bot commands onder de '/p2p' command te laten vallen.  Dit zou ervoor zorgen dat het niet conflicteert met andere bots die evt. in de toekomst toegevoegd worden.

2023-03-17 17:34 UTC, SMWLucasO commented on src/commands/set.ts
> +    .setName('set')
Zie eerdere commentaar over commands

2023-03-17 17:53 UTC, JulianQuispel commented
@SMWLucasO heb je een voorbeeld van hoe je die comments zou willen zien?

2023-03-17 20:51 UTC, JulianQuispel commented on src/commands/notificationChannel.ts
> +    .setName('notification_channel')
Het kan, maar op subcommands kan je niet afdwingen dat deze enkel door een lid met administratieve rechten kan worden aangeroepen vanuit Discord (tot zover ik weet).

2023-03-19 18:15 UTC, SMWLucasO requested changes

2023-03-19 18:15 UTC, SMWLucasO commented on src/commands/notificationChannel.ts
> +        .setDescription('The channel the notification should be send in')
De description mag in het Nederlands

2023-03-19 18:15 UTC, SMWLucasO commented on src/commands/set.ts
> +        .setDescription('Your birthday')
De description mag in het Nederlands

2023-03-20 08:08 UTC, UnderKoen approved these changes

2023-03-20 08:08 UTC, UnderKoen commented on prisma/migrations/20230311134017_add_guild_id_column/migration.sql
Waarom 4 migraties in 1 pr?

2023-03-20 13:27 UTC, JulianQuispel commented on prisma/migrations/20230311134017_add_guild_id_column/migration.sql
De scope van deze PR is eigenlijk te groot doordat ik eigenlijk meerdere taken tegelijkertijd heb opgepakt 🫤

2023-03-20 18:13 UTC, merged